version: '3.8'

services:
  postgres_odoo:
    image: postgres:13
    container_name: odoo-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo_postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_db_net

  odoo:
    image: odoo:17
    container_name: odoo
    depends_on:
      - postgres_odoo
    ports:
      - "8069:8069"
    environment:
      HOST: postgres_odoo
      USER: odoo
      PASSWORD: odoo
      DB_NAME: postgres_odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
    networks:
      - odoo_db_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - odoo_db_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - keycloak_net

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8082:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud_db
    networks:
      - nextcloud_net

  nextcloud_db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - nextcloud_net

  wso2apim:
    build:
      context: .
      dockerfile: Dockerfile-wso2
    image: mi-wso2am:4.1.0
    container_name: wso2apim
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    networks:
      - wso2apim_net

volumes:
  odoo_data:
  odoo_postgres_data:
  odoo_addons:
  nextcloud_data:
  nextcloud_db_data:
  wso2apim_deployment:
  wso2apim_conf:
  wso2apim_resources:
  wso2apim_database:

networks:
  odoo_db_net:
    driver: bridge
  keycloak_net:
    driver: bridge
  nextcloud_net:
    driver: bridge
  wso2apim_net:
    driver: bridge
