version: '3.8'

services:
  postgres_openmrs:
    image: postgres:13
    container_name: openmrs-postgres
    restart: always
    environment:
      POSTGRES_DB: openmrs
      POSTGRES_USER: openmrs
      POSTGRES_PASSWORD: openmrs
    volumes:
      - openmrs_postgres_data:/var/lib/postgresql/data
    networks:
      - openmrs_db_net

  openmrs:
    image: openmrs/openmrs-platform:2.7.0
    container_name: openmrs
    depends_on:
      - postgres_openmrs
    ports:
      - "8081:8080"
    environment:
      DB_DATABASE: openmrs
      DB_HOST: postgres_openmrs
      DB_PORT: 5432
      DB_USERNAME: openmrs
      DB_PASSWORD: openmrs
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      DB_TYPE: postgres
      OMRS_CONFIG_CONNECTION_SERVER: postgres_openmrs
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: openmrs
      OMRS_CONFIG_CONNECTION_PASSWORD: openmrs
      OMRS_CONFIG_CONNECTION_DRIVER: org.postgresql.Driver
      OMRS_CONFIG_CONNECTION_URL: jdbc:postgresql://postgres_openmrs:5432/openmrs
    volumes:
      - openmrs_data:/usr/local/tomcat/.OpenMRS
    networks:
      - openmrs_db_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - openmrs_db_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - keycloak_net

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8082:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud_db
    networks:
      - nextcloud_net

  nextcloud_db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - nextcloud_net

  wso2apim:
    build:
      context: .
      dockerfile: Dockerfile-wso2
    image: mi-wso2am:4.1.0
    container_name: wso2apim
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    networks:
      - wso2apim_net

volumes:
  openmrs_data:
  openmrs_postgres_data:
  nextcloud_data:
  nextcloud_db_data:
  wso2apim_deployment:
  wso2apim_conf:
  wso2apim_resources:
  wso2apim_database:

networks:
  openmrs_db_net:
    driver: bridge
  keycloak_net:
    driver: bridge
  nextcloud_net:
    driver: bridge
  wso2apim_net:
    driver: bridge
