version: '3.8'

services:
  postgres_odoo:
    image: postgres:13
    container_name: odoo-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo_postgres_data:/var/lib/postgresql/data
    networks:
      - proyecto_net

  odoo:
    image: odoo:18
    container_name: odoo
    depends_on:
      - postgres_odoo
    restart: always
    ports:
      - "8069:8069"
    environment:
      HOST: postgres_odoo
      USER: odoo
      PASSWORD: odoo
      DB_NAME: postgres_odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
      - odoo_logs:/var/log/odoo
    networks:
      - proyecto_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8083:8080"
    volumes:
      - adminer_data:/var/www/html
    networks:
      - proyecto_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - proyecto_net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - proyecto_net

networks:
  proyecto_net:
    driver: bridge

volumes:
  odoo_postgres_data:
  odoo_data:
  odoo_addons:
  rabbitmq_data:
    driver: local
  keycloak_data:
    driver: local
  adminer_data:
    driver: local
  odoo_logs:
    driver: local

