FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

# Instalación de Java y utilitarios
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    wget \
    unzip \
    && apt-get clean

# Crear directorio para WSO2
WORKDIR /opt

# Copiar la carpeta descomprimida de WSO2 API Manager al contenedor
COPY wso2am-4.5.0 /opt/wso2am-4.5.0

EXPOSE 9443 8280 8243

# Iniciar el servidor
CMD ["/opt/wso2am-4.5.0/bin/api-manager.sh"]
